service: littleurl

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 128
  stage: dev
  region: eu-west-2

functions:
  app:
    handler: index.handler
    reservedConcurrency: 5
    events:
      - http: GET /